version: '3.8'

services:
  postgres-primary:
    build: 
      context: ./devops_bot/db
      dockerfile: Dockerfile
    container_name: postgres_primary
    networks:
      postgres_net:
        ipv4_address: 192.168.9.100

  postgres-replica-1:
    build:
      context: ./devops_bot/db_repl
      dockerfile: Dockerfile
    container_name: postgres_replica_1
    environment:
      PGDATA: /var/lib/postgresql/data
    volumes:
      - pg_replica1_data:/var/lib/postgresql/data
    command: ["/usr/local/bin/setup-replica.sh"]
    networks:
      postgres_net:
        ipv4_address: 192.168.9.101

  postgres-replica-2:
    build:
      context: ./devops_bot/db_repl
      dockerfile: Dockerfile
    container_name: postgres_replica_2
    environment:
      PGDATA: /var/lib/postgresql/data
    volumes:
      - pg_replica2_data:/var/lib/postgresql/data
    command: ["/usr/local/bin/setup-replica.sh"]
    networks:
      postgres_net:
        ipv4_address: 192.168.9.103

  tg_bot:
    build:
      context: ./devops_bot/bot
      dockerfile: Dockerfile
    container_name: tg_bot
    networks:
      postgres_net:
        ipv4_address: 192.168.9.102

networks:
  postgres_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.9.0/24

volumes:
  pg_replica1_data:
  pg_replica2_data:
