- name: Stop PostgreSQL
  service:
    name: postgresql
    state: stopped

- name: Clean old data
  file:
    path: /var/lib/postgresql/15/main
    state: absent

- name: Clone data from primary
  command: >
    pg_basebackup -h 192.168.1.53 -D /var/lib/postgresql/15/main -U replicator -v -P --wal-method=stream
  become_user: postgres
  environment:
    PGPASSWORD: "debian"

- name: Create recovery config
  copy:
    dest: /var/lib/postgresql/15/main/recovery.conf
    content: |
      standby_mode = 'on'
      primary_conninfo = 'host=192.168.1.53 port=5432 user=replicator password=debian'
      trigger_file = '/tmp/postgresql.trigger.5432'

- name: Start PostgreSQL
  service:
    name: postgresql
    state: started
